on:
  workflow_dispatch: {}
  release:
    types:
      - released

jobs:
  publish-base:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          architecture: x64
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon :base:publish
  publish-linux-amd64:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          architecture: x64
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc libdbus-1-dev libx11-dev cmake ninja-build
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon :jni:publish
  publish-linux-i386:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          architecture: x86
      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y gcc-multilib libdbus-1-dev:i386 libx11-dev:i386 cmake ninja-build
          sudo apt-get install -y zlib1g:i386
      - uses: gradle/gradle-build-action@v2
        env:
          PKG_CONFIG_PATH: /usr/lib/i386-linux-gnu/pkgconfig
        with:
          arguments: --no-daemon :jni:publish
  publish-windows-amd64:
    if: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          architecture: x64
      - uses: lukka/get-cmake@latest
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-toolchain
      - run: Add-Content $env:GITHUB_PATH "C:\msys64\mingw64\bin"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon :jni:publish
  publish-windows-i386:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
#      - uses: actions/setup-java@v3
#        with:
#          distribution: zulu
#          java-version: 17
#          architecture: x86
#      - uses: lukka/get-cmake@latest
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-i686-gcc
      - shell: msys2 {0}
        run: |
          pacman -Ql mingw-w64-i686-gcc
#      - run: |
#          $env:Path = "C:\msys64\mingw32\bin;$env:Path"
#          gcc -v
#          C:\msys64\mingw32\bin\gcc -v
#          .\gradlew.bat --no-daemon :jni:publish
#        env:
#          TOOLCHAINS_ROOT: C:\msys64\mingw32\bin


